#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Package-New
Version  : 0.07
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MR/MRDVT/Package-New-0.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MR/MRDVT/Package-New-0.07.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libpackage-new-perl/libpackage-new-perl_0.07-2.debian.tar.xz
Summary  : Simple base package from which to inherit
Group    : Development/Tools
License  : BSD-3-Clause
Requires: perl-Package-New-license
Requires: perl-Package-New-man

%description
The Package::New object provides a consistent object constructor for
objects.

%package license
Summary: license components for the perl-Package-New package.
Group: Default

%description license
license components for the perl-Package-New package.


%package man
Summary: man components for the perl-Package-New package.
Group: Default

%description man
man components for the perl-Package-New package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Package-New-0.07
mkdir -p %{_topdir}/BUILD/Package-New-0.07/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Package-New-0.07/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Package-New
cp LICENSE %{buildroot}/usr/share/doc/perl-Package-New/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/doc/perl-Package-New/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Package/New.pm
/usr/lib/perl5/site_perl/5.26.1/Package/New/Dump.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Package-New/LICENSE
/usr/share/doc/perl-Package-New/deblicense_copyright

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Package::New.3
/usr/share/man/man3/Package::New::Dump.3
